# Generated by Django 2.2.2 on 2019-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("survey", "0009_auto_20181211_1908")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="random_url",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey",
            name="slug",
            field=models.SlugField(blank=True, max_length=8),
        ),
    ]
